P3ople4u_TechExam/Models/UnusualRateModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace P3ople4u_TechExam.Models
{
    public class UnusualRateModel
    {
        public int Customer { get; set; }
        public int Event { get; set; }
        public int Participant { get; set; }
        public int Stake { get; set; }
        public int Win { get; set; }
        public string Remarks { get; set; }
    }
}

P3ople4u_TechExam/Controllers/RiskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using P3ople4u_TechExam.Models;
using P3ople4u_TechExam.Controllers.ClassFiles;

namespace P3ople4u_TechExam.Controllers
{
    public class RiskController : Controller
    {
        //
        // GET: /Risk/
        public ActionResult Index()
        {
            List<SelectListItem> items = new List<SelectListItem>();
            items.Add(new SelectListItem { Text = "Settled", Value = "Settled" });
            items.Add(new SelectListItem { Text = "Unsettled", Value = "Unsettled" });
            ViewData["Options"] = items;

            return View();
        }

        [HttpPost]
        public ActionResult CheckRates(FormCollection form)
        {
            List<UnusualRateModel> resultList = new List<UnusualRateModel>();

            string dataType = form["Options"].ToString();

            if (dataType == "Settled")
            {
                resultList = ParseSettledData.ParseData();
                ViewBag.Title = "Settled Bet Unusual Data";
            }
            else
            {
                resultList = ParseUnsettledData.ParseData();
                ViewBag.Title = "Unsettled Bet Unusual Data";
            }

            return View(resultList);
        }
	}
}

P3ople4u_TechExam/Views/Risk/CheckRates.cshtml
@model IEnumerable<P3ople4u_TechExam.Models.UnusualRateModel>

<div>
    <h1>@ViewBag.Title</h1>
</div>

@if(Model.Count() > 0)
{
 <table>
    <thead>
        <tr>
            <th>Customer</th>
            <th>Event</th>
            <th>Participant</th>
            <th>Stake</th>
            <th>Win</th>
            <th>Remarks</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Customer</td>
                <td>@item.Event</td>
                <td>@item.Participant</td>
                <td>@item.Stake</td>
                <td>@item.Win</td>
                <td>@item.Remarks</td>
            </tr>
        }
    </tbody>
</table>   
}
else
{
    <span>No unusual data was seen in the records.</span>
}

<div>
    @Html.ActionLink("Go back to Main Page","Index")
</div>

P3ople4u_TechExam/Views/Risk/Index.cshtml
<div>
    <h1>Risk Application</h1>
</div>



<div>
    @using(Html.BeginForm("CheckRates","Risk",FormMethod.Post))
    {
     <table>
        <tr>
            <td>
                <strong>Select Data:</strong>
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                @Html.DropDownList("Options", ViewData["Options"] as SelectList)
            </td>
        </tr>
        <tr>
            <td colspan="3">
                <div style="height:20px"></div>
            </td>
        </tr>
        <tr>
            <td colspan="3" style="text-align:center">
                <input id="btnSubmit" type="submit" value="Submit" />
            </td>
        </tr>
    </table>   
    }
</div>

P3ople4u_TechExam/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Risk Tech Exam</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>